POST https://media-classifier-api.azurewebsites.net/api/gql
Content-Type: application/application/json

query {
    classes {
        id
        name
    }
    media(name: "name.ext") {
        name
        classification {
            class {
                id
                name
            }
            confidence
        }
        entities {
            type
            value
        }
    }
}