POST http://localhost:7071/api/gql
Content-Type: application/application/json

query {
    classes {
        id
        name
    }
    media(name: "test.mp4") {
        name
        class {
            id
            name
        }
        confidence
    }
}