POST https://media-classifier-api.azurewebsites.net/api/gql
Content-Type: application/application/json

query {
    classes {
        id
        name
    }
    media(name: "file.ext") {
        name,
        class {
            id
            name
        }
        confidence
    }
}